//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCapitalMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityHistory()
        {
            this.ReasonActivities = new HashSet<ReasonActivity>();
        }
    
        public long ActivityHistoryId { get; set; }
        public long ActivityId { get; set; }
        public long StatusId { get; set; }
        public System.DateTime ActivityDatetime { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReasonActivity> ReasonActivities { get; set; }
    }
}
