//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCapitalMX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A57E75_chamucolol87Entities : DbContext
    {
        public DB_A57E75_chamucolol87Entities()
            : base("name=DB_A57E75_chamucolol87Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityHistory> ActivityHistories { get; set; }
        public virtual DbSet<ActivityStep> ActivitySteps { get; set; }
        public virtual DbSet<ReasonActivity> ReasonActivities { get; set; }
        public virtual DbSet<ReasonStep> ReasonSteps { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StepHistory> StepHistories { get; set; }
    }
}
