//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCapitalMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonStep
    {
        public long ReasonStepId { get; set; }
        public string Reason { get; set; }
        public long StepHistoryId { get; set; }
    
        public virtual StepHistory StepHistory { get; set; }
    }
}
