//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaCapitalMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StepHistory()
        {
            this.ReasonSteps = new HashSet<ReasonStep>();
        }
    
        public long StepHistoryId { get; set; }
        public long StepActivityId { get; set; }
        public long StatusId { get; set; }
        public System.DateTime StepDatetime { get; set; }
        public long ActivityId { get; set; }
    
        public virtual ActivityStep ActivityStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReasonStep> ReasonSteps { get; set; }
        public virtual Status Status { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Activity Activity { get; set; }
    }
}
